-- CreateTable
CREATE TABLE "ODD_USUARIOS" (
    "ID" TEXT NOT NULL,
    "NOME" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "SENHA" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ODD_USUARIOS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "ODD_CATEGORIAS" (
    "ID" TEXT NOT NULL,
    "NOME" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ODD_CATEGORIAS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "ODD_PRODUTOS" (
    "ID" TEXT NOT NULL,
    "NOME" TEXT NOT NULL,
    "PRECO" TEXT NOT NULL,
    "DESCRICAO" TEXT NOT NULL,
    "BANNER" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "CATEGORIA_ID" TEXT NOT NULL,

    CONSTRAINT "ODD_PRODUTOS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "ODD_OS" (
    "ID" TEXT NOT NULL,
    "TABLE" INTEGER NOT NULL,
    "STATUS" BOOLEAN NOT NULL DEFAULT false,
    "RASCUNHO" BOOLEAN NOT NULL DEFAULT true,
    "NOME" TEXT,
    "CREATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ODD_OS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "ODD_ITEM" (
    "ID" TEXT NOT NULL,
    "QTD" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "OS_ID" TEXT NOT NULL,
    "PRODUTO_ID" TEXT NOT NULL,

    CONSTRAINT "ODD_ITEM_pkey" PRIMARY KEY ("ID")
);

-- AddForeignKey
ALTER TABLE "ODD_PRODUTOS" ADD CONSTRAINT "ODD_PRODUTOS_CATEGORIA_ID_fkey" FOREIGN KEY ("CATEGORIA_ID") REFERENCES "ODD_CATEGORIAS"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ODD_ITEM" ADD CONSTRAINT "ODD_ITEM_OS_ID_fkey" FOREIGN KEY ("OS_ID") REFERENCES "ODD_OS"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ODD_ITEM" ADD CONSTRAINT "ODD_ITEM_PRODUTO_ID_fkey" FOREIGN KEY ("PRODUTO_ID") REFERENCES "ODD_PRODUTOS"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
